import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "../public/assets/css/bootstrap.min.css";
import "../public/assets/css/style.css";
// import "../public/assets/css/magnific-popup.css";
import "../public/assets/css/font-awesome.min.css";
import "../public/assets/css/themify-icons.css";
import "../public/assets/css/nice-select.css";
import "../public/assets/css/flaticon.css";
// import "../public/assets/css/gijgo.css";
// import "../public/assets/css/animate.css";
// import "../public/assets/css/slicknav.css";
// import 'owl.carousel/dist/assets/owl.carousel.css';
// import 'owl.carousel/dist/assets/owl.theme.default.css';
// import "owl.carousel/dist/assets/owl.carousel.css";


// import "../assets/css/style.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-100 text-gray-900`}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
